[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
soulbind = "roS6AMShrJifpsKiAFKoHMvVJPGPHb4SSpHLXVvjEak"

[programs.devnet]
soulbind = "roS6AMShrJifpsKiAFKoHMvVJPGPHb4SSpHLXVvjEak"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
